"""accountNumber not unique

Revision ID: 402a0b2f61aa
Revises: fcfde896591b
Create Date: 2025-04-22 10:47:30.344079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '402a0b2f61aa'
down_revision: Union[str, None] = 'fcfde896591b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('account_number', table_name='bank_accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('account_number', 'bank_accounts', ['account_number'], unique=True)
    # ### end Alembic commands ###
