FROM python:3.12-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de dependencias y las instala
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código
COPY . .

# Expone el puerto en el que correrá la API (por ejemplo, 8000)
EXPOSE 8000

# Ejecuta Uvicorn en modo reload para que detecte cambios en el código
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
