FROM node:22-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia solo los archivos de dependencias primero para aprovechar el cache de Docker
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

# Copia el resto del código
COPY . .

# Expone el puerto en el que corre Next.js (por defecto es 3000)
EXPOSE 3000

# Ejecuta la aplicación en modo desarrollo (con hot reload)
CMD ["npm", "run", "dev"]
